"""Read-only OpenClaw compatibility adapter boundary."""

from .mapping import (
    OpenClawReferenceMapping,
    OpenClawWorkLedgerIds,
    mapping_from_fixture,
    runtime_refs_from_fixture,
    surface_refs_from_fixture,
)
from .readonly import (
    OpenClawMutationBlocked,
    OpenClawReadOnlyAdapter,
    OpenClawReadOnlyInspection,
    artifact_refs_from_fixture,
    guard_read_only_operation,
    invocation_from_fixture,
)
from .weekly_update import (
    WEEKLY_UPDATE_ADOPTION_REPORT_SCHEMA,
    WEEKLY_UPDATE_FIXTURE_SCHEMA,
    WeeklyUpdateAdoptionReport,
    WeeklyUpdateFixture,
    WeeklyUpdateStageObservation,
    adoption_report_from_fixture,
    load_weekly_update_fixture,
    observations_from_weekly_update,
    receipts_from_weekly_update,
    weekly_blackboard_bucket,
    weekly_checked_state,
    weekly_evidence_link,
    weekly_item_id,
    weekly_mode,
    weekly_note_path,
    weekly_owner,
    weekly_source_artifact,
    weekly_update_from_fixture,
)

__all__ = [
    "OpenClawMutationBlocked",
    "OpenClawReadOnlyAdapter",
    "OpenClawReadOnlyInspection",
    "OpenClawReferenceMapping",
    "OpenClawWorkLedgerIds",
    "WEEKLY_UPDATE_ADOPTION_REPORT_SCHEMA",
    "WEEKLY_UPDATE_FIXTURE_SCHEMA",
    "WeeklyUpdateAdoptionReport",
    "WeeklyUpdateFixture",
    "WeeklyUpdateStageObservation",
    "adoption_report_from_fixture",
    "artifact_refs_from_fixture",
    "guard_read_only_operation",
    "invocation_from_fixture",
    "load_weekly_update_fixture",
    "mapping_from_fixture",
    "observations_from_weekly_update",
    "receipts_from_weekly_update",
    "runtime_refs_from_fixture",
    "surface_refs_from_fixture",
    "weekly_blackboard_bucket",
    "weekly_checked_state",
    "weekly_evidence_link",
    "weekly_item_id",
    "weekly_mode",
    "weekly_note_path",
    "weekly_owner",
    "weekly_source_artifact",
    "weekly_update_from_fixture",
]
